-- The claim link, made reachable by a stranger.
--
-- claim_kb() has existed and been tested since 0016, but nothing could show a recipient
-- what they were being offered before asking them to sign up. This migration adds the two
-- things the route needs — a link generator that produces a pasteable URL, and a preview
-- an anonymous visitor can read — plus the one column that makes "already claimed" a
-- representable state at all.
--
-- The token IS the capability. Nothing here is bound to an email address: the founder who
-- receives the link forwards it to whoever actually runs their docs, and that person is the
-- real user. Locking the claim to the addressee breaks the common case.

-- ---------------------------------------------------------------------------
-- 1. Remember which token was consumed
-- ---------------------------------------------------------------------------
-- claim_kb() nulls claim_token on success, so a used token vanishes from the database
-- entirely — "already claimed" and "never existed" were literally the same row state, and
-- no caller change could have told them apart. People re-click links from old emails
-- constantly, so this is the difference between landing in your help center and hitting a
-- not-found.
--
-- A SEPARATE column rather than keeping claim_token set: consumption stays literally true,
-- the unique index on claim_token keeps meaning "one live link", and test_transfer.sh's
-- "claim token consumed" assertion continues to hold.
alter table public.knowledge_bases
  add column if not exists claimed_token uuid,
  add column if not exists claimed_at    timestamptz;

create index if not exists kb_claimed_token_idx
  on public.knowledge_bases (claimed_token)
  where claimed_token is not null;

comment on column public.knowledge_bases.claimed_token is
  'The claim token that was actually spent on this KB. Kept so a re-clicked link can answer "already claimed" instead of "not found" — a used token is otherwise absent from the database entirely.';

-- ---------------------------------------------------------------------------
-- 2. create_claim_link — a pasteable URL, not a bare uuid
-- ---------------------------------------------------------------------------
-- Returns the ASSEMBLED URL on purpose. This gets run by hand for the first thirty demos,
-- and hand-building a link around a copy-pasted uuid is exactly how a dead link reaches a
-- prospect. 30 days, because outreach email sits unread for weeks.
--
-- p_base is a parameter so localhost testing produces a link that actually works, but it
-- defaults to production — the common case must need no arguments beyond the KB.
create or replace function public.create_claim_link(
  p_kb_id uuid,
  p_days  int  default 30,
  p_base  text default 'https://quink.online'
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_token uuid := gen_random_uuid();
begin
  -- auth.uid() is null in a direct database session — the Supabase SQL editor, psql, or
  -- the service role. That is the context this function is FOR: the first thirty demos are
  -- generated by hand, and a helper that refuses the SQL editor is a helper nobody can use.
  -- (Checked live: gating on owns_kb/is_admin alone made it unusable exactly there.)
  --
  -- Safe because `anon` has EXECUTE revoked below, so permission is denied before this body
  -- ever runs for an untrusted caller. Every remaining null-uid caller already holds
  -- credentials that can write the row directly.
  if (select auth.uid()) is not null
     and not (public.owns_kb(p_kb_id) or public.is_admin()) then
    raise exception 'not allowed';
  end if;

  update public.knowledge_bases
     set claim_token      = v_token,
         claim_expires_at = now() + make_interval(days => p_days),
         is_demo          = true
   where id = p_kb_id;

  if not found then
    raise exception 'no such help center';
  end if;

  return rtrim(p_base, '/') || '/claim/' || v_token::text;
end $$;

revoke execute on function public.create_claim_link(uuid, int, text) from anon;
grant  execute on function public.create_claim_link(uuid, int, text) to authenticated;

-- ---------------------------------------------------------------------------
-- 3. claim_preview — show the goods before asking for anything
-- ---------------------------------------------------------------------------
-- Anonymous by design. Bouncing a recipient to a signup form asks them to create an account
-- for something they have not seen; the whole pitch is "look, this is your product,
-- documented". The token holder is entitled to see what they hold.
--
-- Returns FOUR fields and nothing else. Not the owner, not the kb id, not article contents.
-- The kb id in particular is deliberately withheld: handing it to an anonymous caller turns
-- a claim link into a lookup for internal identifiers. The signed-in owner re-clicking a
-- used link gets their kb id from claim_kb() instead, where auth.uid() proves they may
-- have it.
create or replace function public.claim_preview(p_token uuid)
returns table (kb_name text, article_count int, subdomain text, status text)
language sql
stable
security definer
set search_path = public
as $$
  select
    kb.name,
    (select count(*)::int from public.articles a
      where a.kb_id = kb.id and a.visibility = 'listed'),
    kb.subdomain,
    case
      when kb.claimed_token = p_token          then 'claimed'
      when kb.claim_expires_at <= now()        then 'expired'
      else 'valid'
    end
  from public.knowledge_bases kb
  where kb.claim_token = p_token or kb.claimed_token = p_token
  limit 1
$$;

grant execute on function public.claim_preview(uuid) to anon, authenticated;

comment on function public.claim_preview(uuid) is
  'Anonymous preview of a claim link. Returns name, listed-article count, subdomain and status only — never the owner or the kb id. Zero rows means invalid, which deliberately does not distinguish "never existed" from "revoked".';

-- ---------------------------------------------------------------------------
-- 4. claim_kb — record the consumed token, and answer a re-click
-- ---------------------------------------------------------------------------
-- Two changes on top of 0022:
--   * the spent token and the moment are recorded, so claim_preview can say "claimed";
--   * a caller who ALREADY OWNS the KB this token was spent on gets its id back, so
--     re-clicking an old link lands them inside their help center rather than on a dead
--     end. That branch changes no state and answers null for anyone else, so a used link
--     still reveals nothing to a stranger.
--
-- The race is unchanged and needs no lock beyond the one already here: the SELECT ... FOR
-- UPDATE serialises two simultaneous clickers, the second finds claim_token already null,
-- and returns null. The caller treats that as a STATE (re-read the preview, show
-- "claimed"), never as an error.
create or replace function public.claim_kb(p_token uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_kb_id     uuid;
  v_prev      uuid;
  v_new_owner uuid := (select auth.uid());
begin
  if v_new_owner is null then
    raise exception 'must be signed in to claim';
  end if;

  select id, owner_id into v_kb_id, v_prev
    from public.knowledge_bases
   where claim_token = p_token
     and claim_expires_at > now()
   for update;

  if v_kb_id is null then
    -- Not a live token. If it is one THIS caller already spent, hand back the KB so the
    -- re-click lands somewhere useful. Anyone else gets null — same answer as an unknown
    -- token, so a used link is not a probe.
    select id into v_kb_id
      from public.knowledge_bases
     where claimed_token = p_token and owner_id = v_new_owner;
    return v_kb_id;   -- null unless they own it
  end if;

  -- Claiming your own KB is a no-op, not an error, but must not reset the trial clock —
  -- that would be a free 30-day extension for the price of re-clicking a link.
  if v_prev = v_new_owner then
    update public.knowledge_bases
       set claim_token = null, claim_expires_at = null, is_demo = false,
           claimed_token = p_token, claimed_at = now()
     where id = v_kb_id;
    return v_kb_id;
  end if;

  -- EVERY owner-derived reset lives here. Add to this list, not elsewhere.
  update public.knowledge_bases set
      owner_id         = v_new_owner,
      -- The clock starts when THEY take it, not when we built it.
      trial_started_at = now(),
      offline_at       = null,
      purge_at         = null,
      -- The four nudge markers belong to the clock above and reset with it. A claimed KB
      -- whose markers survived would go from "live" to "deleted" in one step, silently.
      trial_day14_email_sent_at   = null,
      trial_day7_email_sent_at    = null,
      trial_offline_email_sent_at = null,
      trial_purged_email_sent_at  = null,
      -- Outreach traffic was ours, not theirs. Zeroing this also un-freezes the address:
      -- migration 0013 locks the subdomain once reader_views > 0, which would otherwise
      -- leave the new owner stuck with whatever we named their help center during
      -- outreach — the first thing they want to change is the one thing they couldn't.
      reader_views     = 0,
      claim_token      = null,
      claim_expires_at = null,
      is_demo          = false,
      -- Not owner-derived: a record of which link was spent, kept so the recipient can
      -- re-click the email they were sent. Never reset.
      claimed_token    = p_token,
      claimed_at       = now()
   where id = v_kb_id;

  -- The previous owner's "last KB" must not point at a KB they no longer own, or our own
  -- next login redirects straight into a customer's help center. This writes to ANOTHER
  -- user's profiles row, and UPDATE on profiles is revoked from `authenticated` — security
  -- definer is what makes this possible, not optional hardening.
  update public.profiles set last_kb_id = null
   where id = v_prev and last_kb_id = v_kb_id;

  -- handle_new_user() provisions a KB on signup, so the reverse-demo path (receive link ->
  -- sign up -> claim) leaves the founder holding TWO KBs on a one-KB plan. That happens on
  -- demo #1, not at some future scale.
  --
  -- If theirs is untouched, bin it: they came for this KB, not a blank one. If it has ANY
  -- content, keep both and let them exceed the limit — over-limit is a far better failure
  -- than deleting something somebody wrote.
  delete from public.knowledge_bases kb
   where kb.owner_id = v_new_owner
     and kb.id <> v_kb_id
     and not exists (select 1 from public.articles a where a.kb_id = kb.id)
     and kb.custom_domain is null
     and kb.reader_views = 0;

  update public.profiles set last_kb_id = v_kb_id where id = v_new_owner;

  return v_kb_id;
end $$;

-- ---------------------------------------------------------------------------
-- 5. A demo looks exactly like what you are about to own
-- ---------------------------------------------------------------------------
-- A demo sits on `internal` (watermark false) and becomes `free` (watermark true) the
-- instant it is claimed — so the thing they accept looks visibly WORSE than the thing they
-- were shown, seconds after saying yes. That is the last impression this funnel should
-- leave.
--
-- Watermark when the owner's plan says so OR the KB is still a demo. The handover then
-- changes nothing visually, and the badge does honest work as an upgrade lever from first
-- contact rather than arriving as a downgrade.
--
-- is_demo KBs remain exempt from the trial sweep for free: they are owned by `internal`,
-- which trial.py filters out by plan.
drop function if exists public.reader_kb(text);

create function public.reader_kb(p_key text)
returns table (
  id uuid, name text, about text, headline text, search_placeholder text,
  primary_color text, font_pairing text,
  logo_path text, favicon_path text, subdomain text, custom_domain text,
  domain_status text, noindex boolean, watermark boolean
)
language sql stable security definer set search_path = public as $$
  select kb.id, kb.name, kb.about, kb.headline, kb.search_placeholder,
         kb.primary_color, kb.font_pairing,
         kb.logo_path, kb.favicon_path, kb.subdomain, kb.custom_domain,
         kb.domain_status, f.noindex, (f.watermark or kb.is_demo)
    from public.knowledge_bases kb
    join public.profiles p on p.id = kb.owner_id
    cross join lateral public.plan_flags(p.plan) f
   where (kb.subdomain = p_key
      or (kb.custom_domain = p_key and kb.domain_status = 'live'))
     and kb.offline_at is null
   limit 1
$$;

grant execute on function public.reader_kb(text) to anon, authenticated;
